### ISSUE TITLE
Unable to install under Windows 10

### ISSUE THREAD

**Issue by Nidonocu** [mscdex/node-mariasql#99] opened 2015-08-08 20:33 UTC
Despite my best efforts of installing the C++ tools for Visual Studio Community 2015, when trying to use the built-in npm tool to install this project or a project that depends on this one, the build fails.

Output from the install logger is here: http://pastebin.com/C2CQWrTk

Any help? I really don't understand why I need to rebuild the native library myself, why can't there be a prebuilt version if you just want to use this library and not edit it?

**Comment by mscdex** [comment] 2015-08-08 21:15
The issue is that VS2015 *finally* implemented `snprintf()`. So there needs to be a check so that the fallback implementation doesn't get used for VS2015. I've added this check now, can you try installing from master?

The reason for no prebuilt binaries IMHO is pretty simple: there is no easy and sane way to do it (yet) as far as I have seen.

**Comment by Nidonocu** [comment] 2015-08-09 15:11
Thanks for the quick reply. I gave it a go and it seems fixing those have unpicked more issues.

Compile log is here: http://pastebin.com/NdDmGkqf

**Comment by mscdex** [comment] 2015-08-09 17:47
Hrmm.... who'd have thought Microsoft would start catching up so much? :wink:

I will install VS2015 and get the further issues fixed.

**Comment by Nidonocu** [comment] 2015-08-09 18:57
Indeed! At least this means as more devs update their systems they won't get caught by this. And thanks, I'll keep an eye out for an update.

**Comment by cpoyraz** [comment] 2015-08-29 12:17
Hi, I also try to install and still it gives error.. would you publish any fix please?

**Comment by haXs** [comment] 2015-09-22 20:05
Hello, Is there a fix for this in the works, I have a project I would love to use this module for but I am on Windows 10 and am stuck at the moment. I would be happy to test if needed.

**Comment by mscdex** [comment] 2015-09-22 23:20
The fix is now in v0.1.24.

**Closed by mscdex** 2015-09-22 23:20 UTC

**Comment by haXs** [comment] 2015-09-23 10:33
When i try i get errors still - Apologies if i am doing something wrong, I am new to this! 

Console out put  - http://pastebin.com/VY7UUUzx
Debug log - http://pastebin.com/Jy3g71rR
